### ISSUE TITLE
Add more fields

### ISSUE THREAD

**Issue by xcesaralejandro** [xcesaralejandro/requeststorer#1]
It would be interesting to have other fields included in the respective requests.

- http_referer
- http_sec_ch_ua
- http_sec_ch_ua_mobile
- http_sec_ch_ua_platform
- http_x_real_ip (Interesting when used in reverse proxy)
- http_x_forwarded_for (Interesting when used in reverse proxy)

**Comment by felimoles** [comment]
#2 see this pr

**Comment by xcesaralejandro** [comment]
Included on release [0.1.2](https://github.com/xcesaralejandro/requeststorer/releases/tag/0.1.2)
